import { CmeContractInterface } from "./cme.contract.interface";
import { CmeContractExchangeEnum } from "./exchange/cme.contract.exchange.enum";
import { CmeContractSectorEnum } from "./sector/cme.contract.sector.enum";
import { CmeContractSymbolEnum } from "./symbol/cme.contract.symbol.enum";

export const CME_CONTRACTS: CmeContractInterface[] =
  // Grouped by contract market sector
  [
    // Per the CME Group futures contracts which Topstep
    // allows its traders to buy/sell positions on
    // https://help.topstep.com/en/articles/8284206-when-and-what-products-can-i-trade#h_fc99007dde

    // Equity
    {
      symbol: CmeContractSymbolEnum.E_MINI_SP_500,
      name: "E-mini S&P 500",
      sector: CmeContractSectorEnum.EQUITY,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.25,
      tickValue: 12.5,
      roundTripFees: 2.8,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_E_MINI_SP_500,
      name: "Micro E-mini S&P 500",
      sector: CmeContractSectorEnum.EQUITY,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.25,
      tickValue: 1.25,
      roundTripFees: 0.74,
    },
    {
      symbol: CmeContractSymbolEnum.E_MINI_NASDAQ,
      name: "E-mini NASDAQ 100",
      sector: CmeContractSectorEnum.EQUITY,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.25,
      tickValue: 5.0,
      roundTripFees: 2.8,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_E_MINI_NASDAQ,
      name: "Micro E-mini NASDAQ 100",
      sector: CmeContractSectorEnum.EQUITY,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.25,
      tickValue: 0.5,
      roundTripFees: 0.74,
    },
    {
      symbol: CmeContractSymbolEnum.E_MINI_RUSSELL,
      name: "E-mini Russell 2000",
      sector: CmeContractSectorEnum.EQUITY,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.1,
      tickValue: 5.0,
      roundTripFees: 2.8,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_E_MINI_RUSSELL,
      name: "Micro E-mini Russell 2000",
      sector: CmeContractSectorEnum.EQUITY,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.1,
      tickValue: 0.25,
      roundTripFees: 0.74,
    },
    {
      symbol: CmeContractSymbolEnum.NIKKEI,
      name: "Nikkei NKD",
      sector: CmeContractSectorEnum.EQUITY,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 5.0,
      tickValue: 25.0,
      roundTripFees: 4.34,
    },
    {
      symbol: CmeContractSymbolEnum.MINI_DOW,
      name: "Mini-DOW",
      sector: CmeContractSectorEnum.EQUITY,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 1.0,
      tickValue: 5.0,
      roundTripFees: 2.8,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_MINI_DOW,
      name: "Micro Mini-DOW",
      sector: CmeContractSectorEnum.EQUITY,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 1.0,
      tickValue: 0.5,
      roundTripFees: 0.74,
    },

    // Foreign Exchange
    {
      symbol: CmeContractSymbolEnum.AUD_USD,
      name: "Australian $",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.00005,
      tickValue: 5.0,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_AUD_USD,
      name: "Micro AUD/USD",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.00005,
      tickValue: 0.5,
      roundTripFees: 0.52,
    },
    {
      symbol: CmeContractSymbolEnum.GBP_USD,
      name: "British Pound",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.0001,
      tickValue: 6.25,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_GBP_USD,
      name: "Micro GBP/USD",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.0001,
      tickValue: 0.625,
      roundTripFees: 0.52,
    },
    {
      symbol: CmeContractSymbolEnum.CAD_USD,
      name: "Canadian $",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.00005,
      tickValue: 5.0,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.EUR_USD,
      name: "Euro FX",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.00005,
      tickValue: 6.25,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_EUR_USD,
      name: "Micro Euro FX",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.00005,
      tickValue: 0.625,
      roundTripFees: 0.52,
    },
    {
      symbol: CmeContractSymbolEnum.E_MINI_EUR_USD,
      name: "E-mini Euro FX",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.0001,
      tickValue: 6.25,
      roundTripFees: 1.74,
    },
    {
      symbol: CmeContractSymbolEnum.JPY_USD,
      name: "Japanese Yen",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.0000005,
      tickValue: 6.25,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.CHF_USD,
      name: "Swiss Franc",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.0001,
      tickValue: 12.5,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.MXN_USD,
      name: "Mexican Peso",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.000025,
      tickValue: 12.5,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.NZD_USD,
      name: "New Zealand $",
      sector: CmeContractSectorEnum.FOREIGN_EXCHANGE,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.0001,
      tickValue: 10.0,
      roundTripFees: 3.24,
    },

    // Live Stock
    {
      symbol: CmeContractSymbolEnum.LEAN_HOGS,
      name: "Lean Hogs",
      sector: CmeContractSectorEnum.LIVE_STOCK,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.00025,
      tickValue: 10.0,
      roundTripFees: 4.24,
    },
    {
      symbol: CmeContractSymbolEnum.LIVE_CATTLE,
      name: "Live Cattle",
      sector: CmeContractSectorEnum.LIVE_STOCK,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.00025,
      tickValue: 10.0,
      roundTripFees: 4.24,
    },

    // Crops
    {
      symbol: CmeContractSymbolEnum.CORN,
      name: "Corn",
      sector: CmeContractSectorEnum.CROPS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.25,
      tickValue: 12.5,
      roundTripFees: 4.3,
    },
    {
      symbol: CmeContractSymbolEnum.WHEAT,
      name: "Wheat",
      sector: CmeContractSectorEnum.CROPS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.25,
      tickValue: 12.5,
      roundTripFees: 4.3,
    },
    {
      symbol: CmeContractSymbolEnum.SOYBEANS,
      name: "Soybeans",
      sector: CmeContractSectorEnum.CROPS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.25,
      tickValue: 12.5,
      roundTripFees: 4.3,
    },
    {
      symbol: CmeContractSymbolEnum.SOYBEAN_MEAL,
      name: "Soybean Meal",
      sector: CmeContractSectorEnum.CROPS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.1,
      tickValue: 10.0,
      roundTripFees: 4.3,
    },
    {
      symbol: CmeContractSymbolEnum.SOYBEAN_OIL,
      name: "Soybean Oil",
      sector: CmeContractSectorEnum.CROPS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.01,
      tickValue: 6.0,
      roundTripFees: 4.3,
    },

    // Gas & Oil
    {
      symbol: CmeContractSymbolEnum.NATURAL_GAS,
      name: "Natural Gas",
      sector: CmeContractSectorEnum.GAS_AND_OIL,
      exchange: CmeContractExchangeEnum.NYMEX,
      tickSize: 0.001,
      tickValue: 10.0,
      roundTripFees: 3.2,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_NATURAL_GAS,
      name: "Micro Henry Hub Natural Gas",
      sector: CmeContractSectorEnum.GAS_AND_OIL,
      exchange: CmeContractExchangeEnum.NYMEX,
      tickSize: 0.001,
      tickValue: 1.0,
      roundTripFees: 1.24,
    },
    {
      symbol: CmeContractSymbolEnum.E_MINI_NATURAL_GAS,
      name: "E-mini Natural Gas",
      sector: CmeContractSectorEnum.GAS_AND_OIL,
      exchange: CmeContractExchangeEnum.NYMEX,
      tickSize: 0.005,
      tickValue: 12.5,
      roundTripFees: 1.04,
    },
    {
      symbol: CmeContractSymbolEnum.RBOB_GASOLINE,
      name: "RBOB Gasoline",
      sector: CmeContractSectorEnum.GAS_AND_OIL,
      exchange: CmeContractExchangeEnum.NYMEX,
      tickSize: 0.0001,
      tickValue: 4.2,
      roundTripFees: 3.04,
    },
    {
      symbol: CmeContractSymbolEnum.CRUDE_OIL,
      name: "Crude Oil",
      sector: CmeContractSectorEnum.GAS_AND_OIL,
      exchange: CmeContractExchangeEnum.NYMEX,
      tickSize: 0.01,
      tickValue: 10.0,
      roundTripFees: 3.04,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_CRUDE_OIL,
      name: "Micro Crude Oil",
      sector: CmeContractSectorEnum.GAS_AND_OIL,
      exchange: CmeContractExchangeEnum.NYMEX,
      tickSize: 0.01,
      tickValue: 1.0,
      roundTripFees: 1.04,
    },
    {
      symbol: CmeContractSymbolEnum.E_MINI_CRUDE_OIL,
      name: "E-mini Crude Oil",
      sector: CmeContractSectorEnum.GAS_AND_OIL,
      exchange: CmeContractExchangeEnum.NYMEX,
      tickSize: 0.025,
      tickValue: 12.5,
      roundTripFees: 2.44,
    },
    {
      symbol: CmeContractSymbolEnum.HEATING_OIL,
      name: "Heating Oil",
      sector: CmeContractSectorEnum.GAS_AND_OIL,
      exchange: CmeContractExchangeEnum.NYMEX,
      tickSize: 0.0001,
      tickValue: 4.2,
      roundTripFees: 3.04,
    },

    // Notes & Bonds
    {
      symbol: CmeContractSymbolEnum.TWO_YEAR_NOTE,
      name: "2-Year Note",
      sector: CmeContractSectorEnum.NOTES_AND_BONDS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.0078125,
      tickValue: 15.625,
      roundTripFees: 1.34,
    },
    {
      symbol: CmeContractSymbolEnum.FIVE_YEAR_NOTE,
      name: "5-Year Note",
      sector: CmeContractSectorEnum.NOTES_AND_BONDS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.0078125,
      tickValue: 15.625,
      roundTripFees: 1.34,
    },
    {
      symbol: CmeContractSymbolEnum.TEN_YEAR_NOTE,
      name: "10-Year Note",
      sector: CmeContractSectorEnum.NOTES_AND_BONDS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.015625,
      tickValue: 15.625,
      roundTripFees: 1.6,
    },
    {
      symbol: CmeContractSymbolEnum.TEN_YEAR_ULTRA_NOTE,
      name: "10-Year Ultra-Note",
      sector: CmeContractSectorEnum.NOTES_AND_BONDS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.015625,
      tickValue: 15.625,
      roundTripFees: 1.64,
    },
    {
      symbol: CmeContractSymbolEnum.THIRTY_YEAR_BOND,
      name: "30-Year Bond",
      sector: CmeContractSectorEnum.NOTES_AND_BONDS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.03125,
      tickValue: 31.25,
      roundTripFees: 1.78,
    },
    {
      symbol: CmeContractSymbolEnum.ULTRA_BOND,
      name: "Ultra-Bond",
      sector: CmeContractSectorEnum.NOTES_AND_BONDS,
      exchange: CmeContractExchangeEnum.CBOT,
      tickSize: 0.03125,
      tickValue: 31.25,
      roundTripFees: 1.94,
    },

    // Metals
    {
      symbol: CmeContractSymbolEnum.GOLD,
      name: "Gold",
      sector: CmeContractSectorEnum.METALS,
      exchange: CmeContractExchangeEnum.COMEX,
      tickSize: 0.1,
      tickValue: 10.0,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_GOLD,
      name: "Micro Gold",
      sector: CmeContractSectorEnum.METALS,
      exchange: CmeContractExchangeEnum.COMEX,
      tickSize: 0.1,
      tickValue: 1.0,
      roundTripFees: 1.24,
    },
    {
      symbol: CmeContractSymbolEnum.SILVER,
      name: "Silver",
      sector: CmeContractSectorEnum.METALS,
      exchange: CmeContractExchangeEnum.COMEX,
      tickSize: 0.005,
      tickValue: 25.0,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_SILVER,
      name: "Micro Silver",
      sector: CmeContractSectorEnum.METALS,
      exchange: CmeContractExchangeEnum.COMEX,
      tickSize: 0.005,
      tickValue: 2.5,
      roundTripFees: 2.04,
    },
    {
      symbol: CmeContractSymbolEnum.COPPER,
      name: "Copper",
      sector: CmeContractSectorEnum.METALS,
      exchange: CmeContractExchangeEnum.COMEX,
      tickSize: 0.0005,
      tickValue: 12.5,
      roundTripFees: 3.24,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_COPPER,
      name: "Micro Copper",
      sector: CmeContractSectorEnum.METALS,
      exchange: CmeContractExchangeEnum.COMEX,
      tickSize: 0.0005,
      tickValue: 1.25,
      roundTripFees: 1.24,
    },
    {
      symbol: CmeContractSymbolEnum.PLATINUM,
      name: "Platinum",
      sector: CmeContractSectorEnum.METALS,
      exchange: CmeContractExchangeEnum.NYMEX,
      tickSize: 0.1,
      tickValue: 5.0,
      roundTripFees: 3.24,
    },

    // Crypto
    {
      symbol: CmeContractSymbolEnum.MICRO_BITCOIN,
      name: "Micro Bitcoin",
      sector: CmeContractSectorEnum.CRYPTO,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 5.0,
      tickValue: 0.5,
      roundTripFees: 2.34,
    },
    {
      symbol: CmeContractSymbolEnum.MICRO_ETHER,
      name: "Micro Ether",
      sector: CmeContractSectorEnum.CRYPTO,
      exchange: CmeContractExchangeEnum.CME,
      tickSize: 0.25,
      tickValue: 0.125,
      roundTripFees: 0.24,
    },
  ];
